"""empty message

Revision ID: 66415f408777
Revises: ee484de3df54
Create Date: 2022-08-08 21:49:21.523900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66415f408777'
down_revision = 'ee484de3df54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_talent')
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'num_upcoming_shows')
    # ### end Alembic commands ###
